# Generated by Django 4.1.7 on 2023-02-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
